### ISSUE TITLE
Hide admin notices and banners from the SiteCare Score and Score History pages

### ISSUE THREAD

**Issue by ryansitecare** [sitecare/sitecare-score#11]
![CleanShot 2024-06-24 at 07 29 07@2x](https://github.com/sitecare/sitecare-score/assets/138807111/3166a70a-3a7e-4c1d-97df-129b6860b16c)

Please do whatever is possible to hide all of these banners.

**Comment by stevezehngut** [comment]
This is ready for testing in the 1.1 branch:

https://github.com/sitecare/sitecare-score/tree/epic/1.1

**Comment by ryansitecare** [comment]
Looks great. Marking this as resolved. Thank you @stevezehngut!
