### ISSUE TITLE
Create admin bar menu link

### ISSUE THREAD

**Issue by ryansitecare** [sitecare/sitecare-score#13]
We want to incorporate an admin bar menu link that displays the SiteCare logo next to a simple colored circle showing the most recent SiteCare Score.

The menu item will display the colored circle only. The numerical value isn't necessary:

![CleanShot 2024-06-24 at 07 34 27@2x](https://github.com/sitecare/sitecare-score/assets/138807111/047a78c7-8c6b-452f-b2c0-e34e13ea4f25)

On hover, the score will display, as well as a link to view most recent issues, and view the score history page.

Designs will be provided.

**Comment by stevezehngut** [comment]
Ready for testing.

**Comment by ryansitecare** [comment]
Looks great @stevezehngut. Functionally it seems to work well. It displays the status color.

This is nitpicky but can we make the baseline position match the other icons in the admin bar menu? https://share.cleanshot.com/2SPfj94v

Also want to make sure we'll still be adding the hover option. Similar to this: https://share.cleanshot.com/j2Lvwns7

It will display a link to the actual score inside the circle, a link to view the most recent report (issues), and a link to view the score history page. 

Bonus would be an arrow indicator (up or down) next to the total score to indicate the change from the previous report.

Is this doable? Should we mock up a design or is this enough info?

**Comment by ryansitecare** [comment]
@stevezehngut here's a mockup

![CleanShot 2024-06-26 at 12 50 23@2x](https://github.com/sitecare/sitecare-score/assets/138807111/ac98b04f-3c5c-45e8-8685-ad5e1e46c176)

**Comment by stevezehngut** [comment]
This is ready to review in v1.1

**Comment by ryansitecare** [comment]
[Here's the design](https://www.figma.com/design/NxzC4YYFF9UD4oigmTPQW5/SiteCare-|-WP-Plugin?node-id=2607-11&t=kBH6r670PgcT4k4Z-0) for the admin bar dropdown menu @stevezehngut.

**Comment by stevezehngut** [comment]
This is ready for your review.

**Comment by ryansitecare** [comment]
One very tiny issue. The arrow color doesn't seem to match the other elements. https://share.cleanshot.com/r3RL95l5

To keep good contrast, red score should have a red arrow, yellow score should have a yellow arrow, and green score should have a green arrow.

Thanks @stevezehngut

**Comment by stevezehngut** [comment]
Good catch! Fixed.

**Comment by ryansitecare** [comment]
Looks good!
