### ISSUE TITLE
Create a dashboard widget

### ISSUE THREAD

**Issue by ryansitecare** [sitecare/sitecare-score#14]
Create a dashboard widget that displays the latest SiteCare Score along with a list of the top 3 action items, and a link to view all issues from the most recent report.

Designs and language to be provided.

**Comment by stevezehngut** [comment]
A first pass of the dashboard widget is now in v1.1

**Comment by stevezehngut** [comment]
@ryansitecare Just checking in. Is there a design ready for this?

**Comment by ryansitecare** [comment]
[Here's the design](https://www.figma.com/design/NxzC4YYFF9UD4oigmTPQW5/SiteCare-|-WP-Plugin?node-id=2607-11&t=kBH6r670PgcT4k4Z-0) for the dashboard widget @stevezehngut. Not sure if the constraints of WordPress will let you implement it that way, so let me know if we need to revise them.

**Comment by stevezehngut** [comment]
The dashboard widget styling ready for review in the latest version.

**Comment by ryansitecare** [comment]
It looks great @stevezehngut. It seems to be missing the Good/Fair/Poor text: https://share.cleanshot.com/VBFrbmyr

**Comment by stevezehngut** [comment]
Please try the latest version.

**Comment by ryansitecare** [comment]
Looks good @stevezehngut. Closing this.
