### ISSUE TITLE
Incorporate email template

### ISSUE THREAD

**Issue by ryansitecare** [sitecare/sitecare-score#15]
Develop the report emails using this email template: https://www.figma.com/design/d0L0UMpU0itiMvVkbMYtNT/SiteCare-Score-Email-Templates?node-id=0-1&t=5oOeYVMrCYZGPoIx-1

Reminder to place an icon with the corresponding severity level next to each item in the Top Issues list.

**Comment by stevezehngut** [comment]
I reviewed the new email template designs. The 1st CTA is "View Full Report" and the 2nd CTA reads "View My Report". Is there a difference in the two?

**Comment by ryansitecare** [comment]
No. They do the same thing. Just different language. Let's make the language "View Report" for both for simplicity and to reduce potential confusion.

**Comment by stevezehngut** [comment]
This is ready to test.

**Comment by ryansitecare** [comment]
Functionally it's great @stevezehngut. Can we make a few small visual edits?


![CleanShot 2024-06-28 at 11 23 54@2x](https://github.com/sitecare/sitecare-score/assets/138807111/ee606fe3-50e3-4d62-ba97-977c82cea6c0)

**Comment by stevezehngut** [comment]
The email template changes are complete.

**Comment by ryansitecare** [comment]
Looks good! Closing this out.
