### ISSUE TITLE
Create new Scheduled Scans feature

### ISSUE THREAD

**Issue by ryansitecare** [sitecare/sitecare-score#16]
Add a scheduled job that runs a scan of the website once every day.

Along with that, the following will be added for on-demand requests.
* A limit of 5 on-demand requests per day to be implement server side
* Whenever an on-demand request is initiated, a message will be displayed to the user letting them know they have used [1 of 5 on-demand scans]
* Once the on-demand daily scan limit has been reached, a message will be displayed to have the user check back in on the following day.

Designs for this messaging will be provided.

**Comment by stevezehngut** [comment]
Daily scans are now in place on v1.1. A good way to test this is to use the "Advanced Cron Manager" plugin. It will allow you to execute a cron job.

Automated scans do not send an email when they complete. 

In progress:
- A limit of 5 on-demand requests per day to be implement server side
- Whenever an on-demand request is initiated, a message will be displayed to the user letting them know they have used [1 of 5 on-demand scans]
- Once the on-demand daily scan limit has been reached, a message will be displayed to have the user check back in on the following day.

**Comment by stevezehngut** [comment]
Daily limit is in place now in v1.1. When the limit is reached, the latest report is displayed. Added a notification to the report screen that says the limit has been reached. I will update when I receive the new designs.

**Comment by ryansitecare** [comment]
@stevezehngut here are designs (and language) for the metered scans:

1. [Standard language](https://www.figma.com/design/NxzC4YYFF9UD4oigmTPQW5/SiteCare-|-WP-Plugin?node-id=2601-5&t=kBH6r670PgcT4k4Z-0)
2. [Limit reached language](https://www.figma.com/design/NxzC4YYFF9UD4oigmTPQW5/SiteCare-|-WP-Plugin?node-id=2601-351&t=kBH6r670PgcT4k4Z-0)

**Comment by stevezehngut** [comment]
Which version do you prefer?

**Comment by ryansitecare** [comment]
@stevezehngut we'll use the language from 1 and 2, but let's use the design from 1. Thanks!

**Comment by stevezehngut** [comment]
Ready for review.

**Comment by ryansitecare** [comment]
Works like a dream. Closing this.
