### ISSUE TITLE
Score History page enhancements

### ISSUE THREAD

**Issue by ryansitecare** [sitecare/sitecare-score#17]
Add the following new enhancements to the score history page
* At the top of the page display a running timeline of the histories to show improvement or decline over time
* Add a column to the table view of past scans showing whether the scan is on-demand or automated
* Retain the previous 60 days of scans in the table view
* Retain 1 year of score history for the timeline view

Designs will be provided for this.

**Comment by stevezehngut** [comment]
Added a chart to the history page in v1.1.

**Comment by stevezehngut** [comment]
@ryansitecare Are there any changes needed for this feature?
