### ISSUE TITLE
Report results page enhancement

### ISSUE THREAD

**Issue by ryansitecare** [sitecare/sitecare-score#18]
Once a scan completes and the report view is displayed, we'd like to include a link/button some way to easily get to the Score History page without needing to navigate back to the sidebar menu.

**Comment by ryansitecare** [comment]
@stevezehngut [here's a design](https://www.figma.com/design/NxzC4YYFF9UD4oigmTPQW5/SiteCare-|-WP-Plugin?node-id=2610-214&t=tWPyxyi1XeNWu3me-0) that incorporates a "View Past Reports" button into the screen. It's a little bit subtle, on purpose, so it's there as an option but doesn't pull attention from the main report.

**Comment by stevezehngut** [comment]
Ready for review.

**Comment by ryansitecare** [comment]
Looks great!
