### ISSUE TITLE
Scan Runs but Doesn't Redirect to Report

### ISSUE THREAD

**Issue by darah-sitecare** [sitecare/sitecare-score#19]
I ran into an issue on the following sites where the scan would say it was running, but it never redirected to the reports page. The scan shows up in the Score History, though. 

- georgialandsurveying.com 
- gloverdavis.com
- glsarchives.com
- hallsatlanta.com
- godivasalon.com 

[georgialandsurveying.txt](https://github.com/user-attachments/files/16052862/georgialandsurveying.txt)
[gloverdavis.txt](https://github.com/user-attachments/files/16052863/gloverdavis.txt)
[glsarchives.txt](https://github.com/user-attachments/files/16052864/glsarchives.txt)
[godivasalon.txt](https://github.com/user-attachments/files/16052865/godivasalon.txt)
[hallsatlanta.txt](https://github.com/user-attachments/files/16052866/hallsatlanta.txt)

**Comment by stevezehngut** [comment]
Where are these hosted?

**Comment by stevezehngut** [comment]
I just deployed a fix that should address this issue. It looks like the report was stalling when a dev or beta version of a plugin was being used.

**Comment by stevezehngut** [comment]
Is this issue still happening?

**Comment by darah-sitecare** [comment]
Nope! It's fixed. Thank you!
