### ISSUE TITLE
CSS won't load 

### ISSUE THREAD

**Issue by darah-sitecare** [sitecare/sitecare-score#20]
All or most of the plugin's CSS won't load for the following sites: 

wichitachec.com
Screenshot _Scan My Site_: https://share.cleanshot.com/pFF88FPW
Screenshot _Score History_: https://share.cleanshot.com/B6FR5l3W

gbq.com
Screenshot _Report_: https://share.cleanshot.com/J8MC8jlR
Screenshot _Score History_: https://share.cleanshot.com/vDxfT67K

**Comment by stevezehngut** [comment]
Thank you. What version of the plugin?

**Comment by darah-sitecare** [comment]
1.0.4 for both

**Comment by darah-sitecare** [comment]
SIte Info for both:

**gbq.com**

`
### wp-core ###

version: 6.5.4
site_language: en_US
user_language: en_US
timezone: America/New_York
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: undefined
environment_type: production
user_count: 130
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /nas/content/live/gbqstaging
wordpress_size: loading...
uploads_path: /nas/content/live/gbqstaging/wp-content/uploads
uploads_size: loading...
themes_path: /nas/content/live/gbqstaging/wp-content/themes
themes_size: loading...
plugins_path: /nas/content/live/gbqstaging/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (2) ###

advanced-cache.php: true
object-cache.php: true

### wp-active-theme ###

name: GBQ (gbq-2017)
version: 1.9.6
author: Buckeye Interactive
author_website: http://buckeyeinteractive.com
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, post-thumbnails, menus, custom-logo, title-tag, html5, widgets
theme_path: /nas/content/live/gbqstaging/wp-content/themes/gbq-2017
auto_update: Disabled

### wp-themes-inactive (1) ###

Twenty Twenty-Three: version: 1.4, author: the WordPress team, Auto-updates disabled

### wp-mu-plugins (6) ###

Force Strong Passwords - WPE Edition: version: 1.8.0, author: Jason Cosper
WP Engine Cache Plugin: version: 1.3.1, author: WP Engine
WP Engine Seamless Login Plugin: version: 1.6.1, author: WP Engine
WP Engine Security Auditor: version: 1.1.1, author: wpengine
WP Engine System: version: 5.0.1, author: WP Engine
WP Migrate Compatibility: version: 1.3, author: Delicious Brains

### wp-plugins-active (40) ###

Advanced Custom Fields PRO: version: 6.3.2.1, author: WP Engine (latest version: 6.3.3), Auto-updates disabled
Akismet Anti-spam: Spam Protection: version: 5.3.2, author: Automattic - Anti-spam Team, Auto-updates disabled
All in One SEO: version: 4.6.3, author: All in One SEO Team (latest version: 4.6.5), Auto-updates disabled
Breadcrumb NavXT: version: 7.3.0, author: John Havlik (latest version: 7.3.1), Auto-updates disabled
Check & Log Email: version: 1.0.12.1, author: checkemail (latest version: 1.0.13), Auto-updates disabled
Checkout Field Editor for WooCommerce (Pro): version: 3.6.3, author: ThemeHigh, Auto-updates disabled
Classic Editor: version: 1.6.3, author: WordPress Contributors, Auto-updates disabled
Disable XML-RPC: version: 1.0.1, author: Philip Erb, Auto-updates disabled
Gravity Forms: version: 2.8.12, author: Gravity Forms (latest version: 2.8.13), Auto-updates disabled
Gravity Forms HubSpot Add-On: version: 2.1.0, author: Gravity Forms, Auto-updates disabled
Gravity Forms SendGrid Add-On: version: 1.6.0, author: Gravity Forms, Auto-updates disabled
GTM4WP - A Google Tag Manager (GTM) plugin for WordPress: version: 1.20.2, author: Thomas Geiger, Auto-updates disabled
HubSpot All-In-One Marketing - Forms, Popups, Live Chat: version: 11.1.21, author: HubSpot (latest version: 11.1.22), Auto-updates disabled
Imagify: version: 2.2.2, author: Imagify – Optimize Images & Convert WebP & Avif, Auto-updates disabled
Media Cleaner: version: 6.7.6, author: Jordy Meow (latest version: 6.7.7), Auto-updates disabled
Melapress File Monitor: version: 2.0.2, author: Melapress, Auto-updates disabled
Multiple Columns for Gravity Forms: version: 4.0.6, author: WebHolism, Auto-updates disabled
Password Policy Manager: version: 2.0.1, author: miniOrange, Auto-updates disabled
Patchstack Security: version: 2.2.12, author: Patchstack, Auto-updates enabled
Redirection: version: 5.4.2, author: John Godley, Auto-updates disabled
Regenerate Thumbnails: version: 3.1.6, author: Alex Mills (Viper007Bond), Auto-updates disabled
Relevanssi: version: 4.22.2, author: Mikko Saari, Auto-updates disabled
Seriously Simple Podcasting: version: 3.4.0, author: Castos, Auto-updates disabled
Simple History: version: 4.15.1, author: Pär Thernström, Auto-updates enabled
SiteCare Score: version: 1.0.4, author: SiteCare, Auto-updates disabled
Software libraries for WP Activity Log: version: 2.0.0, author: Melapress, Auto-updates disabled
SVG Support: version: 2.5.5, author: Benbodhi, Auto-updates disabled
The Events Calendar: version: 6.5.0.1, author: The Events Calendar (latest version: 6.5.1.5), Auto-updates disabled
Training Videos Feature: version: 0.1.0, author: Cardinal Solutions, Eric Katz, Auto-updates disabled
Two Factor: version: 0.9.1, author: Plugin Contributors, Auto-updates disabled
Web Accessibility by accessiBe: version: 1.18, author: accessiBe, Auto-updates disabled
WooCommerce: version: 8.9.3, author: Automattic (latest version: 9.0.2), Auto-updates disabled
WooCommerce Stripe Gateway: version: 8.3.1, author: WooCommerce (latest version: 8.4.0), Auto-updates disabled
WordPress Backup & Security Plugin - BlogVault: version: 5.56, author: Backup by BlogVault, Auto-updates disabled
WordPress Importer: version: 0.8.2, author: wordpressdotorg, Auto-updates disabled
WP Activity Log (Premium): version: 5.0.0, author: Melapress, Auto-updates disabled
WP Mail Logging: version: 1.12.0, author: WP Mail Logging Team, Auto-updates disabled
WP SEO Structured Data Schema: version: 2.7.10, author: WPSEMPlugins, Auto-updates disabled
WPS Hide Login: version: 1.9.16.6, author: WPServeur, NicolasKulka, wpformation (latest version: 1.9.16.7), Auto-updates disabled
WP Video Popup: version: 2.9.7, author: David Vongries, Auto-updates disabled

### wp-plugins-inactive (1) ###

WP Activity Log: version: 5.0.0, author: Melapress, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1691
imagemagick_version: ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: 1
post_max_size: 100M
upload_max_filesize: 50M
max_effective_size: 50 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 137 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 6144
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 9.22337203685E+18
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, AVI, AVIF, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HEIC, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIDEO, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: 2.3.0
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: not available

### the-events-calendar ###


### wp-server ###

server_architecture: Linux 5.4.0-1069-gcp x86_64
httpd_software: Apache
php_version: 8.2.19 64bit
php_sapi: apache2handler
max_input_variables: 10000
time_limit: 3600
memory_limit: 512M
max_input_time: 3600
upload_max_filesize: 50M
php_post_max_size: 100M
curl_version: 7.81.0 OpenSSL/3.0.2
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true
current: 2024-07-03T19:28:44+00:00
utc-time: Wednesday, 03-Jul-24 19:28:44 UTC
server-time: 2024-07-03T15:28:42-04:00

### wp-database ###

extension: mysqli
server_version: 8.0.36-28
client_version: mysqlnd 8.2.19
max_allowed_packet: 16777216
max_connections: 500

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /nas/content/live/gbqstaging/wp-content
WP_PLUGIN_DIR: /nas/content/live/gbqstaging/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8
DB_COLLATE: utf8_unicode_ci

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### aioseo (1) ###

noindexed: Date Archives, Search Page, Attachments (attachment), Categories (category)

### acf ###

version: 6.3.2.1
plugin_type: PRO
activated: true
activated_url: https://gbq.com
license_type: Developer
license_status: active
subscription_expires: undefined
ui_field_groups: 0
php_field_groups: 0
json_field_groups: 62
rest_field_groups: 0
post_types_enabled: true
ui_post_types: 26
json_post_types: 0
ui_taxonomies: 14
json_taxonomies: 0
ui_options_pages_enabled: true
ui_options_pages: 0
json_options_pages: 0
php_options_pages: 2
rest_api_format: light
registered_acf_blocks: 0
blocks_per_api_version: 
blocks_per_acf_block_version: 
blocks_using_post_meta: 0
preload_blocks: true
admin_ui_enabled: true
field_type-modal_enabled: true
field_settings_tabs_enabled: false
shortcode_enabled: true
registered_acf_forms: 0
json_save_paths: 1
json_load_paths: 1

`

**wichitachec.com**

`
### wp-core ###

version: 6.5.5
site_language: en_US
user_language: en_US
timezone: America/Chicago
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 2
default_comment_status: open
environment_type: production
user_count: 2
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /dom31032
wordpress_size: loading...
uploads_path: /dom31032/wp-content/uploads
uploads_size: loading...
themes_path: /dom31032/wp-content/themes
themes_size: loading...
plugins_path: /dom31032/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-active-theme ###

name: Churchope (churchope)
version: 1.11
author: themoholics
author_website: http://themoholics.com/
parent_theme: none
theme_features: core-block-patterns, menus, post-thumbnails, automatic-feed-links, editor-style, widgets, widgets-block-editor
theme_path: /dom31032/wp-content/themes/churchope

### wp-themes-inactive (1) ###

Twenty Twenty-Three: version: 1.4, author: the WordPress team

### wp-mu-plugins (3) ###

Pagely Management V2: version: 2.0.64, author: Pagely
WP Migrate Compatibility: version: 1.3, author: Delicious Brains
_patchstack.php: author: (undefined), version: (undefined)

### wp-plugins-active (13) ###

Akismet Anti-spam: Spam Protection: version: 5.3.2, author: Automattic - Anti-spam Team
Classic Editor: version: 1.6.3, author: WordPress Contributors
Crowdsignal Polls & Ratings: version: 3.1.1, author: Automattic, Inc.
Gallery Bank - WordPress Gallery Plugin: version: 4.0.50, author: Tech Banker
Gravity Forms: version: 2.8.13, author: Gravity Forms
Patchstack Security: version: 2.2.12, author: Patchstack
SendGrid: version: 1.11.8, author: SendGrid
Simple History: version: 4.15.1, author: Pär Thernström
SiteCare Score: version: 1.0.4, author: SiteCare
SlideOnline for WordPress: version: 1.2.1, author: Julian Magnone
Twitter Widget Pro: version: 2.9.0, author: Aaron D. Campbell
WordPress Backup & Security Plugin - BlogVault: version: 5.56, author: Backup by BlogVault
WP Migrate: version: 2.6.13, author: WP Engine

### wp-plugins-inactive (1) ###

Viper's Video Quicktags: version: 6.6.0, author: Viper007Bond

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1691
imagemagick_version: ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: 1
post_max_size: 200M
upload_max_filesize: 200M
max_effective_size: 200 MB
max_file_uploads: 50
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 7 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 786432
	imagick::RESOURCETYPE_MAP: 7 GB
	imagick::RESOURCETYPE_MEMORY: 2 GB
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 9.2233720368548E+18
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, AVI, AVIF, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HEIC, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIDEO, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, BMP
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 5.15.0-1063-aws x86_64
httpd_software: Apache
php_version: 8.1.29 64bit
php_sapi: fpm-fcgi
max_input_variables: 10000
time_limit: 6000
memory_limit: 1024M
max_input_time: 60
upload_max_filesize: 200M
php_post_max_size: 200M
curl_version: 7.74.0 OpenSSL/1.1.1w
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true
current: 2024-07-03T19:29:23+00:00
utc-time: Wednesday, 03-Jul-24 19:29:23 UTC
server-time: 2024-07-03T14:29:23-05:00

### wp-database ###

extension: mysqli
server_version: 8.0.32
client_version: mysqlnd 8.1.29
max_allowed_packet: 536870912
max_connections: 3000

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /dom31032/wp-content
WP_PLUGIN_DIR: /dom31032/wp-content/plugins
WP_MEMORY_LIMIT: 1024M
WP_MAX_MEMORY_LIMIT: 1024M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

`

**Comment by stevezehngut** [comment]
I believe this should be working as expected now. Please let me know.

**Comment by stevezehngut** [comment]
Is this issue still happening?

**Comment by darah-sitecare** [comment]
Thanks for following up, and sorry for the delay! Both are showing the same style issues. They're both still running 1.0.4, and no update is available. Should there have been an update?

**Comment by ryansitecare** [comment]
wichitachec.com has a theme conflict that breaks styles all over the admin. It isn't limited to the SiteCare Score plugin. I activated Twenty TwentyThree and the styles load correctly.

With version 1.1, gbq.com is loading the styles. This was breaking previously because the site has an active Content Security Policy. Now that all of the styles/assets are loaded locally instead of remotely, the assets can load.

I'm going to close this issue as it appears to pass be working correctly with 1.1 installed.
