### ISSUE TITLE
Military Time vs AM/PM

### ISSUE THREAD

**Issue by ryansitecare** [sitecare/sitecare-score#21]
@stevezehngut if we're using military time we probably don't want AM/PM next to it.

Although I learn toward using standard time (ie 7:32 PM) since that's what we see in most UX. Thoughts?

![CleanShot 2024-07-11 at 18 59 13@2x](https://github.com/user-attachments/assets/f9b0c8d7-652a-4d8c-b2de-77897e78b4b7)

**Comment by stevezehngut** [comment]
Fixed in the latest version
