### ISSUE TITLE
Admin bar score doesn't match report scores

### ISSUE THREAD

**Issue by ryansitecare** [sitecare/sitecare-score#22]
This is something I've been able to recreate on several websites. The admin menu bar score doesn't match the report score.

![CleanShot 2024-07-18 at 14 05 18@2x](https://github.com/user-attachments/assets/520756d6-7313-49a5-b526-361ac10bed3d)

**Comment by stevezehngut** [comment]
Can you please add a few of the URLs where this is showing up?

**Comment by ryansitecare** [comment]
@stevezehngut it looks like this is the behavior on all sites. Or at least all that I've tested so far. All sites show a score of 65 in the admin bar.

* It's occurring on sites where I've installed the plugin for the first time
* It's occurring on sites that have been upgraded from a previous version

Here are some sample domains:
* ryandsullivan.com
* sitecare.com
* damndelicious.net
* i4color.com

**Comment by stevezehngut** [comment]
Investigating now.

**Comment by stevezehngut** [comment]
Try the latest version. I added an exception that does not display the toolbar if no score history exists.

**Comment by ryansitecare** [comment]
It doesn't seem to have changed anything @stevezehngut. Even on a site that already has a score history, I ran a new scan after installing the latest version, and it's still showing 65 in the admin bar.

I used an incognito browser for testing to make sure the issues weren't related to caching somehow.

![CleanShot 2024-07-19 at 12 35 37@2x](https://github.com/user-attachments/assets/c1fc6ea2-aa0f-4260-b1dc-ea57c56b50e6)

**Comment by stevezehngut** [comment]
Hmmmm. Is this screen shot from sitecare.com?

**Comment by ryansitecare** [comment]
Yes @stevezehngut this screenshot is from SiteCare.com

**Comment by stevezehngut** [comment]
Fixed in the latest version

**Comment by ryansitecare** [comment]
Yep looks like this is all sorted.
