### ISSUE TITLE
Syntax error - doesn't allow plugin to be activated

### ISSUE THREAD

**Issue by ryansitecare** [sitecare/sitecare-score#23]
I've encountered the following syntax/fatal error when attempting to activate the plugin on several sites:

`PHP Parse error:  syntax error, unexpected '|', expecting ';' or '{' in /wp-content/plugins/sitecare-score-epic-1.1/includes/class-data.php on line 135`

**Comment by stevezehngut** [comment]
Hmm, I am not able to reproduce that. It may be related to the php version. What version of php are you running?

I did push a fix that should address it.

**Comment by ryansitecare** [comment]
I just tested the latest and the issue is still there. It's PHP version 7.4.33 @stevezehngut.

**Comment by stevezehngut** [comment]
Please try again with the latest version

**Comment by ryansitecare** [comment]
This is fixed. Thank you @stevezehngut!. I'm closing this issue and I think we're ready to do the 1.1 release. I'll send you over some new screenshots later today.

**Comment by ryansitecare** [comment]
We got this same error with the live roll out of 1.1.0 @stevezehngut. It happened on this site: shorelineunitarian.org. It's PHP 7.4.33.6. This may end up impacting more sites. Let me know if you want/need an export of this site to test it.

**Comment by stevezehngut** [comment]
Deployed v 1.1.1. This will fix the issue.
