### ISSUE TITLE
Critical Error on Score History page

### ISSUE THREAD

**Issue by darah-sitecare** [sitecare/sitecare-score#24]
The following error occurred on the Score History page:

`Fatal error: Uncaught TypeError: array_reverse(): Argument #1 ($array) must be of type array, null given in /var/www/html/site/public_html/wp-content/plugins/sitecare-score/includes/class-history.php:68 Stack trace: #0 /var/www/html/site/public_html/wp-content/plugins/sitecare-score/includes/class-history.php(68): array_reverse(NULL) #1 /var/www/html/site/public_html/wp-content/plugins/sitecare-score/includes/class-history.php(33): SiteCare\History->history_chart(NULL) #2 /var/www/html/site/public_html/wp-includes/class-wp-hook.php(324): SiteCare\History->init('') #3 /var/www/html/site/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array) #4 /var/www/html/site/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #5 /var/www/html/site/public_html/wp-admin/admin.php(259): do_action('sitecare-score_...') #6 {main} thrown in /var/www/html/site/public_html/wp-content/plugins/sitecare-score/includes/class-history.php on line 68`

It seems this only occurs when there isn't a history of scans to display.

**Comment by stevezehngut** [comment]
Great find! Please download the latest plugin from github and try it now. (v 1.1.2). 

I added functionality that hides the history tab until a scan has been performed. The logic also hides the dashboard widget and the toolbar.

**Comment by darah-sitecare** [comment]
Looks like this solution works! Thank you for your quick fix!
