### ISSUE TITLE
Add links to Fail and Alert states for theme and plugin issues that are flagged

### ISSUE THREAD

**Issue by ryansitecare** [sitecare/sitecare-score#5]
Can we add a simple link to the end of the following statements?
- Inactive themes
- Outdated active themes
- Abandoned active themes
- Outdated active plugins
- Inactive plugins

The text will simply say "Review available theme updates." (or plugin updates) like this: https://share.cleanshot.com/qNtNHytq. 

And then it would link to the appropriate theme or plugin page:
- `/wp-admin/themes.php`
- `wp-admin/plugins.php?plugin_status=inactive`
- `/wp-admin/plugins.php?plugin_status=upgrade`

**Comment by stevezehngut** [comment]
Done
